apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{ include "model-serving.fullname" . }}
  labels:
    {{- include "model-serving.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      {{- include "model-serving.selectorLabels" . | nindent 6 }}
  strategy:
    canary:
      canaryService: {{ include "model-serving.fullname" . }}-canary
      stableService: {{ include "model-serving.fullname" . }}-stable
      steps:
        - setWeight: 20
        - pause: { duration: 30s }
        - analysis:
            templates:
              - templateName: model-serving-latency
        - setWeight: 50
        - pause: { duration: 30s }
        - analysis:
            templates:
              - templateName: model-serving-latency
  template:
    metadata:
      labels:
        {{- include "model-serving.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: model-serving
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8080
