replicaCount: 1
image:
  repository: myorg/model-serving
  tag: "1.0.0"
  pullPolicy: IfNotPresent
service:
  port: 80
analysis:
  prometheusAddress: http://prometheus-server.default.svc.cluster.local
