apiVersion: v1
kind: Service
metadata:
  name: {{ include "model-monitor.fullname" . }}
  labels:
    {{- include "model-monitor.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: metrics
      port: {{ .Values.service.port }}
      targetPort: metrics
  selector:
    {{- include "model-monitor.selectorLabels" . | nindent 4 }}
